# Generated by Django 4.2 on 2023-05-01 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_link_link_alter_link_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='link',
            new_name='address',
        ),
    ]
